# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba32fd9606768e1069e4db1419c00e47f7725a07631a66dacb97d49069ea39b7ea476c82ce4f934e11aaa3f6dfefc9129af3426716c6f05425b7832f875646ef

test:
  secret_key_base: 6dceb87be4e90ee37e31db9b409acdba41bfa930fc8af158f3cb33a61832e6cd6a5268f87afbd08313896e675ab759c7aed8e33b5c4d56987d40ab55730fd0f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
